/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Template;

import Template.front.scenes.SceneLoader;
import Template.front.scenes.Scenes;
import javafx.application.Application;
import javafx.stage.Stage;

public class Main extends Application {

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage stage_) {
        Scenes.templateScene = SceneLoader.load("TemplateScene");

        stage_.setTitle("Template");
        stage_.setWidth(1280);
        stage_.setHeight(720);
        stage_.setScene(Scenes.templateScene);
        stage_.show();
    }
}
